services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - restaurant_service
      - order_service

  user_service:
    build:
      context: ../user
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - CASSANDRA_HOST=host.docker.internal # Use the host's IP for Cassandra
    ports:
      - "8000:8000"

  restaurant_service:
    build:
      context: ../restaurant
      dockerfile: Dockerfile
    container_name: restaurant_service
    environment:
      - CASSANDRA_HOST=host.docker.internal # Use the host's IP for Cassandra
    ports:
      - "8002:8002"

  order_service:
    build:
      context: ../order
      dockerfile: Dockerfile
    container_name: order_service
    environment:
      - CASSANDRA_HOST=host.docker.internal # Use the host's IP for Cassandra
    ports:
      - "8003:8003"
