services:
  nginx:
    networks:
      - app_network
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - restaurant_service
      - order_service

   cassandra-db:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    networks:
      - app_network
    

  user_service:
    build:
      context: ../user
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - CASSANDRA_HOST=cassandra # Use the host's IP for Cassandra
    ports:
      - "8000:8000"
    networks:
      - app_network

  restaurant_service:
    build:
      context: ../restaurant
      dockerfile: Dockerfile
    container_name: restaurant_service
    environment:
      - CASSANDRA_HOST=cassandra # Use the host's IP for Cassandra
    ports:
      - "8002:8002"
    networks:
      - app_network

  order_service:
    build:
      context: ../order
      dockerfile: Dockerfile
    container_name: order_service
    environment:
      - CASSANDRA_HOST=cassandra # Use the host's IP for Cassandra
    ports:
      - "8003:8003"
    networks:
      - app_network
